[Authority]
  Identifier = "authority-2.example.org"
  Addresses = ["127.0.0.1:30003"]
  DataDir = "/home/user/go/src/github.com/katzenpost/hypothetical-network-config/authority-2"

[[Authorities]]
  Addresses = ["127.0.0.1:30004"]
  IdentityPublicKey = "AOiE/ApCTuWvhr9gGkSNzkI2FYUFIkY/uyYedhzb+9A="
  LinkPublicKey = "EWrWXPU0HjgbFuqegT2oY5b+JoZ1U9N8isnQ38mieEk="

[[Authorities]]
  Addresses = ["127.0.0.1:30005"]
  IdentityPublicKey = "t7c63oH9Xa4njiAottXroUGWB4omzuvqAjAjuhHrUdY="
  LinkPublicKey = "K/Q6fkgQ79UhBtf/4QYqEuvS8EBzoOykq4VkCx9ib1I="

[[Authorities]]
  Addresses = ["127.0.0.1:30001"]
  IdentityPublicKey = "zsbPxFL2qbpXm5j0pYvOfoeOFav2M0GwSW8hB4Bzjf8="
  LinkPublicKey = "Ff4ZfZaU1IvSoQEVmVWjDvF6zAqFPyqnqkuJi1WRP34="

[[Authorities]]
  Addresses = ["127.0.0.1:30002"]
  IdentityPublicKey = "se0Ar8sB6UWlJZCXV+4TN7WxAPxNtPSpXtxdqTS6MLQ="
  LinkPublicKey = "4hMrN3HG7Zmlmy4vG2H0I956YQmys8B0U4PyaBOMR34="

[Logging]
  Disable = false
  File = "katzenpost.log"
  Level = "DEBUG"

[Parameters]
  MixLambda = 1.0
  MixMaxDelay = 10000
  SendLambda = 123.0
  SendShift = 12
  SendMaxInterval = 123456
  DropLambda = 0.0
  DropShift = 0
  DropMaxInterval = 0
  LoopLambda = 0.0
  LoopShift = 0
  LoopMaxInterval = 0

[Debug]
  Layers = 3
  MinNodesPerLayer = 1
  GenerateOnly = false

[[Mixes]]
  Identifier = ""
  IdentityKey = "Q/LlUppkMeFNgJUs0YZUPoUvr9LEVzlvWsEHMxY0TsY="

[[Mixes]]
  Identifier = ""
  IdentityKey = "TwER6fx4nZavQZ0+NnPCct/l/Utouqnxg9PgMPo034E="

[[Mixes]]
  Identifier = ""
  IdentityKey = "yed6F75L1bN3dZ4GIJtTH9oFBz/Hwu49CT1iBXXvExc="

[[Mixes]]
  Identifier = ""
  IdentityKey = "MLRCexvulMmQ7p4V+RKV99m7hTmawpg43v6qBUztIkQ="

[[Mixes]]
  Identifier = ""
  IdentityKey = "7P3dtIcyhdXMyJUCTeRADVTtashuq7fFlGp1V6YRc+o="

[[Mixes]]
  Identifier = ""
  IdentityKey = "2mWeFLgR9gG6PoAJh26No05C6Mcww2KiMg7gm35lFUw="

[[Providers]]
  Identifier = "provider-0.example.org"
  IdentityKey = "rYE6ON1FsENOVA5PV3cIPGJvM/3aJR67wPoNKVbjOO0="

[[Providers]]
  Identifier = "provider-1.example.org"
  IdentityKey = "7YPw0+fvoncb+/rxOxNvp8QjrL8cwUaUM4QK4ZySbd0="
