[Server]
  Identifier = "provider-0.example.org"
  Addresses = ["127.0.0.1:30006"]
  DataDir = "/home/user/go/src/github.com/katzenpost/hypothetical-network-config/provider-0"
  IsProvider = true

[Logging]
  Disable = false
  File = "katzenpost.log"
  Level = "DEBUG"

[Provider]
  EnableUserRegistrationHTTP = false
  BinaryRecipients = false
  CaseSensitiveRecipients = false
  RecipientDelimiter = ""
  [Provider.AltAddresses]
    TCP = ["localhost:30006"]
    torv2 = ["onedaythiswillbea.onion:2323"]
  [Provider.UserDB]
    Backend = "bolt"
    [Provider.UserDB.Bolt]
      UserDB = "/home/user/go/src/github.com/katzenpost/hypothetical-network-config/provider-0/users.db"
  [Provider.SpoolDB]
    Backend = "bolt"
    [Provider.SpoolDB.Bolt]
      SpoolDB = "/home/user/go/src/github.com/katzenpost/hypothetical-network-config/provider-0/spool.db"

  [[Provider.Kaetzchen]]
    Capability = "loop"
    Endpoint = "+loop"
    Disable = false

  [[Provider.Kaetzchen]]
    Capability = "keyserver"
    Endpoint = "+keyserver"
    Disable = false

[PKI]
  [PKI.Voting]

    [[PKI.Voting.Peers]]
      Addresses = ["127.0.0.1:30001"]
      IdentityPublicKey = "zsbPxFL2qbpXm5j0pYvOfoeOFav2M0GwSW8hB4Bzjf8="
      LinkPublicKey = "Ff4ZfZaU1IvSoQEVmVWjDvF6zAqFPyqnqkuJi1WRP34="

    [[PKI.Voting.Peers]]
      Addresses = ["127.0.0.1:30002"]
      IdentityPublicKey = "se0Ar8sB6UWlJZCXV+4TN7WxAPxNtPSpXtxdqTS6MLQ="
      LinkPublicKey = "4hMrN3HG7Zmlmy4vG2H0I956YQmys8B0U4PyaBOMR34="

    [[PKI.Voting.Peers]]
      Addresses = ["127.0.0.1:30003"]
      IdentityPublicKey = "GG8KJKrhP3ZO7VhhhuGp9+D79BruYObQyGyx/3GlRmI="
      LinkPublicKey = "lzjczeHS5uYpc0f59mG3VySGIOCRFI4a7ld9PZvx7jc="

    [[PKI.Voting.Peers]]
      Addresses = ["127.0.0.1:30004"]
      IdentityPublicKey = "AOiE/ApCTuWvhr9gGkSNzkI2FYUFIkY/uyYedhzb+9A="
      LinkPublicKey = "EWrWXPU0HjgbFuqegT2oY5b+JoZ1U9N8isnQ38mieEk="

    [[PKI.Voting.Peers]]
      Addresses = ["127.0.0.1:30005"]
      IdentityPublicKey = "t7c63oH9Xa4njiAottXroUGWB4omzuvqAjAjuhHrUdY="
      LinkPublicKey = "K/Q6fkgQ79UhBtf/4QYqEuvS8EBzoOykq4VkCx9ib1I="

[Management]
  Enable = true
  Path = "/home/user/go/src/github.com/katzenpost/hypothetical-network-config/provider-0/management_sock"

[Debug]
  NumSphinxWorkers = 2
  NumProviderWorkers = 1
  NumKaetzchenWorkers = 3
  SchedulerExternalMemoryQueue = false
  SchedulerQueueSize = 0
  SchedulerMaxBurst = 16
  UnwrapDelay = 10
  ProviderDelay = 500
  KaetzchenDelay = 750
  SchedulerSlack = 10
  SendSlack = 50
  DecoySlack = 15000
  ConnectTimeout = 60000
  HandshakeTimeout = 30000
  ReauthInterval = 30000
  SendDecoyTraffic = false
  DisableRateLimit = false
  GenerateOnly = false
