[Server]
  Identifier = "node-0"
  Addresses = ["127.0.0.1:30008"]
  OnlyAdvertiseAltAddresses = false
  DataDir = "/data"
  IsProvider = false
  [Server.AltAddresses]
    TCP = ["localhost:30008"]
    torv2 = ["onedaythiswillbea.onion:2323"]

[Logging]
  Disable = false
  File = "katzenpost.log"
  Level = "DEBUG"

[PKI]
  [PKI.Voting]

    [[PKI.Voting.Peers]]
      Addresses = ["127.0.0.1:30001"]
      IdentityPublicKey = "kuk4Sc1qn3a9rdWlxynn/tUMKdPaxmEoxDQE1zb3UnE="
      LinkPublicKey = "FsMTXuwKvPBFmsGkJbL/3gKGxwHGr74XcvuILXUz3nw="

    [[PKI.Voting.Peers]]
      Addresses = ["127.0.0.1:30002"]
      IdentityPublicKey = "J9EJ+sAGjsXWRDfZkMYW0dj4cZwwNjIKae/dMjmJ/3I="
      LinkPublicKey = "f0dOKc4H+E9rjlAaohEIbD1JaVoS/DqjsXahMdAJeA8="

    [[PKI.Voting.Peers]]
      Addresses = ["127.0.0.1:30003"]
      IdentityPublicKey = "bmW7Jz84UUkrjvNwrvNpHtpjgtkCD6OtqUil4TXIaP8="
      LinkPublicKey = "P+a8ZgMrCnuP4GpMZxn84CGOsEry9aem0rndjMbmbiE="

    [[PKI.Voting.Peers]]
      Addresses = ["127.0.0.1:30004"]
      IdentityPublicKey = "dFgsC6tV+fOO8RsWQ/YTp0IUGtNgLF4dFU1daHYF5BM="
      LinkPublicKey = "Ee2V620CjX441YkuLSO/ms00lGuE91mBs7JcoG/nbVY="

    [[PKI.Voting.Peers]]
      Addresses = ["127.0.0.1:30005"]
      IdentityPublicKey = "dFjR45iIO6B6+VIsk+lIu3TZYCmxsXcUi2tK1AXOeXU="
      LinkPublicKey = "C2zxCX8HLmlZ6X9gyMpdzf/SGMrHApfAnlvmw0jj5ww="

[Management]
  Enable = false
  Path = "/home/user/go/src/github.com/katzenpost/hypothetical-network-config/node-0/management_sock"

[Debug]
  NumSphinxWorkers = 2
  NumProviderWorkers = 1
  NumKaetzchenWorkers = 3
  SchedulerExternalMemoryQueue = false
  SchedulerQueueSize = 0
  SchedulerMaxBurst = 16
  UnwrapDelay = 10
  ProviderDelay = 500
  KaetzchenDelay = 750
  SchedulerSlack = 10
  SendSlack = 50
  DecoySlack = 15000
  ConnectTimeout = 60000
  HandshakeTimeout = 30000
  ReauthInterval = 30000
  SendDecoyTraffic = false
  DisableRateLimit = false
  GenerateOnly = false
